### ISSUE TITLE
#配置求助！

### ISSUE THREAD

**Issue by ShirakamiFubuk1** [2512500960/zzu-minieap-openwrt#3]
现在已经有了编译好的软件包，但是在设置页面里面的锐捷认证还是叫mentohust（虽然pc的也叫这），不知道是不是高级设置里面需要什么特殊设置，保存应用后连不上，公众号也显示账号离线

**Comment by 2512500960** [comment]
> 现在已经有了编译好的软件包，但是在设置页面里面的锐捷认证还是叫mentohust（虽然pc的也叫这），不知道是不是高级设置里面需要什么特殊设置，保存应用后连不上，公众号也显示账号离线

设置页面？minieap只有命令行啊，你那个luci-app-界面，调用的哪个客户端去认证的？

**Comment by ShirakamiFubuk1** [comment]
时luci-app-mentohust，可能是帮忙编译那哥们操作错了吧，我说为啥minieap找不到指令
