### ISSUE TITLE
openwrt上无法使用

### ISSUE THREAD

**Issue by vvsz** [2512500960/zzu-minieap-openwrt#4]
按步骤编译了一个openwrt的安装包，设置网口ip，启动后无法查找认证服务器。坐标主校区松园，win端那个软件可以使用。
![Snipaste_2022-06-19_19-15-28](https://user-images.githubusercontent.com/107537433/174478468-8aade24e-f9e4-4914-8641-8b93e6a4113d.png)

**Comment by 2512500960** [comment]
网口信息给看一下？或者直接加qq远程？

**Comment by vvsz** [comment]
> 网口信息给看一下？或者直接加qq远程？
![Snipaste_2022-06-19_20-31-10](https://user-images.githubusercontent.com/107537433/174481178-064962c7-7be2-4366-9740-2683ad250aaa.png)

**Comment by 2512500960** [comment]
1. 你用来连接校园网的网卡是eth1，你命令行里-i 参数跟的啥。
2. 你这截图直接暴露ip了，还是加qq说吧。

**Comment by 2512500960** [comment]
通过增加参数 -a 1解决，这个宿舍区域应该用私有广播地址。
